name: ESLint Code Analysis

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      ### Lint client folder
      - name: Install dependencies (client)
        working-directory: ./client
        run: npm install

      - name: Run ESLint on client
        working-directory: ./client
        run: |
          mkdir -p ../reports
          npx eslint . --format @microsoft/eslint-formatter-sarif --output-file ../reports/eslint-client.sarif || true

      ### Lint server folder
      - name: Install dependencies (server)
        working-directory: ./server
        run: npm install

      - name: Run ESLint on server
        working-directory: ./server
        run: |
          npx eslint . --format @microsoft/eslint-formatter-sarif --output-file ../reports/eslint-server.sarif || true

      ### Combine or Upload SARIF (optional)
      - name: Upload SARIF report (client)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/eslint-client.sarif

      - name: Upload SARIF report (server)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/eslint-server.sarif
