name: ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:18
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl -f http://localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        volumes:
          - .:/app
        working-directory: /app
        command: bash -c "npm install && npm start"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for web service to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:3000 && break || sleep 5
          done

      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'ghcr.io/zaproxy/zaproxy'
          allow_fail: false
          rules_file_name: '.zap/rules.tsv' # Optional: customize scan rules
          cmd_options: '-a' # aggressive scan

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
